# Generated by Django 3.1.2 on 2020-11-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descrpition',
            new_name='description',
        ),
    ]
