# Generated by Django 3.1.2 on 2020-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
