# Generated by Django 3.1.3 on 2020-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created_at'),
        ),
    ]
