# Generated by Django 3.1.2 on 2020-11-15 10:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoicequestion',
            name='answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='SubmittedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openforms.openform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openforms.submittedform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openforms.multichoicequestion')),
            ],
        ),
    ]
