# Generated by Django 3.1.3 on 2020-11-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
