# Generated by Django 3.1.3 on 2020-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_assignmentfile_submittedassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='turned_in',
        ),
        migrations.AddField(
            model_name='submittedassignment',
            name='turned_in',
            field=models.BooleanField(default=False),
        ),
    ]
